Start scratch of be_kind.md
nikomatsakis/rustacean-principles pull request #10
Opened 2021-09-23 23:55 UTC by marcospb19

2021-09-23 23:58 UTC, marcospb19 commented
With very opinionated points on how to behave in open-source :slightly_smiling_face: .

I think it's lacking talking about being kind to beginners, as they have a hard time starting to contribute, usually because of insecurity.

2021-09-24 09:59 UTC, nikomatsakis commented
Oh, interesting! I definitely prefer this version. I've been thinking about how to alter "Be kind" based on @matklad's feedback. Some of the themes bounding around in my head were:

* Benefit of the doubt -- people are rarely out to get you, so the question is, can we find what they *are* after? There's probably something useful or important there. 
* Being forgiving -- people make mistakes

These may just be separate principles.

Maybe we should quote Maya Angelou: “I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.”

2021-09-24 13:01 UTC, nikomatsakis requested changes
Minor nit

2021-09-24 13:01 UTC, nikomatsakis commented on src/how_to_rustacean/be_kind.md
> +Rust is being built and used by different people from around the globe, everyone got a personal opinion when it comes to what is the best for the language, so disagreements are inevitable.
```suggestion
Rust is being built and used by different people from around the globe and everyone has their own opinion on what is the best for the language, so disagreements are inevitable.
```

2021-09-24 17:48 UTC, marcospb19 commented on src/how_to_rustacean/be_kind.md
> +Rust is being built and used by different people from around the globe, everyone got a personal opinion when it comes to what is the best for the language, so disagreements are inevitable.
Updated :+1:.

2021-09-24 17:48 UTC, marcospb19 commented
> Some of the themes bounding around in my head were:
>
> - Benefit of the doubt -- people are rarely out to get you, so the question is, can we find what they _are_ after? There's probably something useful or important there.
> - Being forgiving -- people make mistakes
>
> These may just be separate principles.

The first one seems more like a tip to dealing better with people than a principle.

I think that both are close enough to go on the same page.

"being forgiving" fits better with **Be kind and considerate** than "benefit of the doubt", however, this page is already talking about how to deal with other people, so it's probably the best place to insert more thoughts about it.

2021-09-24 17:49 UTC, marcospb19 commented
I left this PR on

2021-09-24 17:51 UTC, marcospb19 commented
I liked the quote, but am not sure how to insert it, I left this PR with "Allow edits from maintainers" checked, so feel free to make any changes before merging.

2023-12-07 14:11 UTC, closed without merging